#!/usr/bin/env bash

DOTFILES=$(cd $(dirname  "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.local/bin/tmux-cht.sh
ln -s $DOTFILES/scripts/tmux-cht.sh $HOME/.local/bin/tmux-cht.sh

rm -rf $HOME/.tmux-cht-command
ln -s $DOTFILES/tmux/.tmux-cht-command $HOME/.tmux-cht-command

rm -rf $HOME/.tmux-cht-languages
ln -s $DOTFILES/tmux/.tmux-cht-languages $HOME/.tmux-cht-languages

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.config/aerospace
ln -s $DOTFILES/aerospace $HOME/.config/aerospace
